import { Share } from "react-native";
import * as Clipboard from "expo-clipboard";
import * as FileSystem from "expo-file-system";

export interface ReportSections {
  nameCommon: string;
  nameScientific: string;
  confidence: number;
  safetyStatus: string;
  description: string;
  uses: string[];
  warnings: string[];
  traditionalUses: string[];
  localNames: Record<string, string>;
  traditionalKnowledge: string[];
  medicinalUses: string[];
  safetyNotes: string[];
  ecology: string[];
  conservation: string[];
  nutritionalProfile: string[];
  activeCompounds: string[];
  healthBenefits: string[];
  overview: string | null;
}

function bullet(items: string[]): string {
  return items.map((i) => `  • ${i}`).join("\n");
}

export function buildReportText(s: ReportSections): string {
  const lines: string[] = [
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    `RUZIVO PLANT REPORT`,
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    `Plant: ${s.nameCommon}`,
    `Scientific Name: ${s.nameScientific}`,
    `Safety: ${s.safetyStatus}`,
    `Confidence: ${Math.round(s.confidence * 100)}%`,
    "",
  ];

  if (s.description) {
    lines.push("DESCRIPTION", s.description, "");
  }

  if (s.overview) {
    lines.push("OVERVIEW", s.overview, "");
  }

  const localEntries = Object.entries(s.localNames ?? {});
  if (localEntries.length > 0) {
    lines.push("LOCAL NAMES");
    localEntries.forEach(([lang, name]) => lines.push(`  ${lang}: ${name}`));
    lines.push("");
  }

  if (s.uses.length > 0) {
    lines.push("USES", bullet(s.uses), "");
  }

  if (s.warnings.length > 0) {
    lines.push("WARNINGS", bullet(s.warnings), "");
  }

  if (s.traditionalUses.length > 0) {
    lines.push("TRADITIONAL AFRICAN USES", bullet(s.traditionalUses), "");
  }

  if (s.traditionalKnowledge.length > 0) {
    lines.push("TRADITIONAL KNOWLEDGE", bullet(s.traditionalKnowledge), "");
  }

  if (s.medicinalUses.length > 0) {
    lines.push("TRADITIONAL USES", bullet(s.medicinalUses), "");
  }

  if (s.safetyNotes.length > 0) {
    lines.push("SAFETY NOTES", bullet(s.safetyNotes), "");
  }

  if (s.ecology.length > 0) {
    lines.push("ECOLOGY & HABITAT", bullet(s.ecology), "");
  }

  if (s.conservation.length > 0) {
    lines.push("CONSERVATION NOTES", bullet(s.conservation), "");
  }

  if (s.nutritionalProfile.length > 0) {
    lines.push("NUTRITIONAL & HEALING PROFILE", bullet(s.nutritionalProfile), "");
  }

  if (s.activeCompounds.length > 0) {
    lines.push("ACTIVE COMPOUNDS", bullet(s.activeCompounds), "");
  }

  if (s.healthBenefits.length > 0) {
    lines.push("POTENTIAL HEALTH BENEFITS", bullet(s.healthBenefits), "");
  }

  lines.push(
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "For educational purposes only. Not a substitute for professional medical advice.",
    "Generated by RUZIVO — Plant Knowledge. Offline First."
  );

  return lines.join("\n");
}

export async function copyReportToClipboard(text: string): Promise<void> {
  await Clipboard.setStringAsync(text);
}

export async function shareReport(
  text: string,
  plantName: string
): Promise<void> {
  await Share.share({
    message: text,
    title: `RUZIVO — ${plantName} Plant Report`,
  });
}

export async function exportReportAsTextFile(
  text: string,
  plantName: string
): Promise<void> {
  const slug = plantName.toLowerCase().replace(/\s+/g, "_");
  const filename = `ruzivo_${slug}_${Date.now()}.txt`;
  const uri = `${FileSystem.cacheDirectory}${filename}`;
  await FileSystem.writeAsStringAsync(uri, text, {
    encoding: FileSystem.EncodingType.UTF8,
  });
  await Share.share({
    message: text,
    title: `RUZIVO — ${plantName} Report`,
  });
}
