uploads = []
generated = []

[[outputs]]
id = "v48axwi2TSkJ9rIpwcOGO"
uri = "file://attached_assets/image_search/photo-1502082553048-f009c37129b9.jpg"
type = "image"
title = "Candidate 1"

[[outputs]]
id = "wXqBRHHtpaXvR_drSn1nY"
uri = "file://attached_assets/image_search/photo-1550159930-40066082a4fc.jpg"
type = "image"
title = "Candidate 2"

[[outputs]]
id = "NQlqKLF0uR0cDKaXfYilJ"
uri = "file://attached_assets/image_search/photo-1545569341-9eb8b30979d9.jpg"
type = "image"
title = "Candidate 3"

[[outputs]]
id = "u47zcUdS4i8lUYDC4HrvA"
uri = "file://attached_assets/image_search/photo-1596638787647-904d822d751e.jpg"
type = "image"
title = "Candidate 4"
